### ISSUE TITLE
Visualizations: when date is chosen for overlay, legend text is wrong

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/plot.data#100]
I'm using the PRISM2 study & `Death date`, which has 3 unique values:  2018-05-13, 2018-10-30, and 2019-01-24

When I select a date variable with < 8 unique values as my overlay variable, the legend does not look right (says "Data" instead of the date):

![image](https://user-images.githubusercontent.com/25450900/135678431-d702a668-c1a0-4be3-a22a-e59d70e2c02a.png)

**Comment by d-callan** [comment]
plot.data v1.3.0 rserve 1.4.0

**Comment by aaronwlsong** [comment]
Tested this issue in the same study, looks good now. closing ticket. 

![image](https://user-images.githubusercontent.com/61077845/136602654-3dd32649-0445-49c9-8a80-7c91146c4b5d.png)

**Comment by danicahelb** [comment]
Reopening as the overlay labels are problematic in other graphs, such as scatter:

using the PRISM2 study:
![image](https://user-images.githubusercontent.com/25450900/136637910-6d4520b2-5d97-4b64-8051-983ce9ae7d4f.png)

@d-callan please check overlay behavior on all plot types before closing ticket again. Thanks!
