### ISSUE TITLE
Backend: data[number].facetVariableDetails is not always an array

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/plot.data#108]
The Data API specifies always an array
```
mosaic.data[].facetVariableDetails | array | Max. items: 2
```
Yet when I make this GEMS1 request it's just a single object not in an array:

POST
```
{
	"config": {
		"facetVariable": [
			{
				"entityId": "EUPATH_0035127",
				"variableId": "ENVO_00000009"
			}
		],
		"outputEntityId": "EUPATH_0000096",
		"xAxisVariable": {
			"entityId": "EUPATH_0000096",
			"variableId": "EUPATH_0010367"
		},
		"yAxisVariable": {
			"entityId": "EUPATH_0000096",
			"variableId": "EUPATH_0011048"
		}
	},
	"filters": [
		{
			"entityId": "EUPATH_0035127",
			"stringSet": [
				"India"
			],
			"type": "stringSet",
			"variableId": "ENVO_00000009"
		}
	],
	"studyId": "GEMSCC0003-1"
}
``` 
Response (part of)
```
{
	"facetVariableDetails": {
		"variableId": "ENVO_00000009",
		"entityId": "EUPATH_0035127",
		"value": "India"
	}
}
```

The troublemaking facet variable is Country.

When I use `Case or control participant` the response is correctly array-like:
```
{
	"facetVariableDetails": [
		{
			"variableId": "EUPATH_0010375",
			"entityId": "EUPATH_0000096",
			"value": "Case"
		}
	]
}
```

Sorry I haven't tried more variables/entities to figure out more of an explanation.

**Comment by d-callan** [comment]
its pretty specifically only a problem when there is a single value for a single strata var. thats why its more apparent in mosaic, bc there is one facet and no overlay.

**Comment by bobular** [comment]
Thanks + tested :+1:

**Comment by nkittur-uga** [comment]
Backend issues, cannot be directly QAed by outreach team. Moving to complete.
