### ISSUE TITLE
Mosaic statsTable facetVariableDetails is malformed when request's showMissingness == TRUE

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/plot.data#109]
GEMS1

POST
```
{
	"config": {
		"facetVariable": [
			{
				"entityId": "EUPATH_0000096",
				"variableId": "EUPATH_0010151"
			}
		],
		"outputEntityId": "EUPATH_0000096",
		"showMissingness": "TRUE",
		"xAxisVariable": {
			"entityId": "EUPATH_0000096",
			"variableId": "EUPATH_0010367"
		},
		"yAxisVariable": {
			"entityId": "EUPATH_0000096",
			"variableId": "EUPATH_0011048"
		}
	}
}
```

Gives a response with the "EntityID.VariableID" keys that we got rid of a while ago.
```
{
	"statsTable": [
		{
			"chisq": 1514.3406,
			"pvalue": 0,
			"degreesFreedom": 4,
			"EUPATH_0000096.EUPATH_0010151": "No"
		},
		{
			"chisq": 7968.819,
			"pvalue": 0,
			"degreesFreedom": 4,
			"EUPATH_0000096.EUPATH_0010151": "No data"
		},
		{
			"chisq": 697.3865,
			"pvalue": 1.2827e-149,
			"degreesFreedom": 4,
			"EUPATH_0000096.EUPATH_0010151": "Yes"
		}
	]
}
```

Here's the correctly formed response from the same request but with `showMissingness: 'FALSE'`

```
{
	"statsTable": [
		{
			"chisq": 1514.3406,
			"pvalue": 0,
			"degreesFreedom": 4,
			"facetVariableDetails": [
				{
					"variableId": "EUPATH_0010151",
					"entityId": "EUPATH_0000096",
					"value": "No"
				}
			]
		},
		{
			"chisq": 697.3865,
			"pvalue": 1.2827e-149,
			"degreesFreedom": 4,
			"facetVariableDetails": [
				{
					"variableId": "EUPATH_0010151",
					"entityId": "EUPATH_0000096",
					"value": "Yes"
				}
			]
		}
	]
}
```

**Comment by d-callan** [comment]
there shouldnt be a statsTable when showMissingness is TRUE

**Comment by SheenaTomko** [comment]
Not sure if this needs to be reopened or is a separate issue:
In GEMS 1, tried making a 2x2 table with X-axis = Given antibiotic before stool collection, Y-axis = Aeromonas, by bacteriology, and facet = Age group. When I turned on the "no data" toggle, I saw the following error message. 
<img width="1174" alt="Screen Shot 2021-11-12 at 3 30 27 PM" src="https://user-images.githubusercontent.com/54597319/141536951-998f9c13-eed6-4e49-9988-9e981b4b5466.png">

**Comment by nkittur-uga** [comment]
Mosaic 2x2 plots have numerous bugs and are not working for me. Trying the same plot shown by Sheena's screenshot above gave me this error: 

500 Internal Server Error {"status":"server-error","message":"Unable to complete processing","requestId":"1NCkP2xlR0uFE3rYrhLzhW"}

**Comment by bobular** [comment]
> Mosaic 2x2 plots have numerous bugs and are not working for me. Trying the same plot shown by Sheena's screenshot above gave me this error:
> 
> 500 Internal Server Error {"status":"server-error","message":"Unable to complete processing","requestId":"1NCkP2xlR0uFE3rYrhLzhW"}

And the 500 error appears before attempting faceting.

I believe this is because there are no participants with values for "given antibiotic before stool collection" (my subset is heavily filtered)
![image](https://user-images.githubusercontent.com/308639/142423451-dec113a1-55e0-41c7-b307-4104c375ee32.png)

Did we ever really sort out completely empty plots?

**Comment by bobular** [comment]
Yes, looks like we did (see barplot below) but maybe mosaic is late to the party?

![image](https://user-images.githubusercontent.com/308639/142423856-1ceaf391-05d8-438d-8fe5-dd51dfc8d21f.png)

**Comment by SheenaTomko** [comment]
Moving this to complete because now the system doesn't allow you to turn on facets if there is no missing data for the facet variable
