### ISSUE TITLE
Backend: make sure response makes sense for collection vars

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/plot.data#116]
decided the response, when it contains a collection var, should provide var specs for the parent and child terms as well as explicitly stating it contains a collection var. need to make sure were doing this (bc i think we prev said wed try to provide the display labels rather than the specs).

**Comment by asizemore** [comment]
To clarify, right now we return the following as part of the plot config:
```      "listVariableDetails": {
        "variableId": [
          "contB",
          "contA",
          "contC"
        ],
        "entityId": [
          "entity",
          "entity",
          "entity"
        ]
```
This holds information about each variable chosen as part of the collection var.

Instead, we want something like
```
"xAxisVariableDetails":
  "variableId": "myVarId"
  "entityId": "entity"

"yAxisVariableDetails":
  "variableId": "myOtherVarId"
  "entityId": "entity"
```
where `myVarId` would have the vocabulary "contA, contB, contC" and `myOtherVarId` would be the new continuous variable.

We also want to remove all display names for collection vars, and add some sort of "containsCollectionVar" flag. 

Did I understand that all correctly?

**Comment by d-callan** [comment]
i think the variableId + entityId combo is a VariableSpec. so i think any axis that can represent a collection var needs to be able to return an array of VariableSpecs. 
"xAxisVariableDetails":[
  {"variableId": "myVarId"
  "entityId": "entity"},
 {"variableId": "myVarId2"
  "entityId": "entity"}]

xAxisVariableDetails i think can also probably gain some sort of flag something like 'isCollectionVariable' indicating it represents a collection var. then if it is a collection w a single child selected then its still displayed consistently w other collections. 
yAxisVariableDetails possibly needs to gain a flag indicating its the collection value. think we can infer entity id for the var spec and make something up for the var id i suppose.
this implies the data service gains a VariableDetails object w these two things as optional properties.
that leaves specifying the parent var spec somehow. that may end up being relevant to the viz generally as opposed to individual axes, im not sure. but i think maybe for that we add something like 'collectionParentVariableSpec' to the plot config.

youll need a PR here as well as the data service for this one as well, as we finalize the api.

**Comment by d-callan** [comment]
think that also means the StrataVariableDetails object in the data service will likely need updating to use the new VariableDetails rather than VariableSpec

**Comment by asizemore** [comment]
After discussion on 12/14, we'll assume what we have is fine and treat everything new like a bug. Closing with the expectation that we'll open many new issues on the topic soon :)
