### ISSUE TITLE
Non-compliant barplot response with case/control overlay but not with another overlay var

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/plot.data#121]
GEMS1
No filters
![image](https://user-images.githubusercontent.com/308639/145444678-2798e6ff-93db-4ff1-bdc1-cc23fcbd5da2.png)

Here's part of the erroneous response for barplot.data[0]
```
{
	"overlayVariableDetails": [
		{
			"variableId": "EUPATH_0010375",
			"entityId": "EUPATH_0000096",
			"value": "Case"
		}
	]
}
```
`overlayVariableDetails` should be an object, not an array of objects.

With another variable, e.g. Participant->Age group, it works fine (returns an object, not an array)

**Comment by bobular** [comment]
I just spotted this again when overlaying by country in Kalifabougou Malaria Cohort.  Again, no filters.

I think it happens when the overlay variable has only one value (in this case 'Mali')

**Comment by danicahelb** [comment]
alternatively, we could add the legend even if it only contains one value. I will add this to a future UX meeting agenda
