### ISSUE TITLE
Mbio: add new arg to map for imputing 0s

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/plot.data#126]
Once imputing 0s function is ready, need to add a flag in the map so that the data service can send var-specific info to plot.data about imputing 0s.

**Comment by SheenaTomko** [comment]
@asizemore this is already assigned to you and was moved to "Ready for testing"

**Comment by asizemore** [comment]
Thanks @SheenaTomko !! 

Confirmed all looks good. Moving to Complete.
