### ISSUE TITLE
Apps: box and scatter to take `rankedValues`

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/plot.data#142]
Like pie plot, should take and respect ranked values. Will also need to know plot reference.

**Comment by asizemore** [comment]
Should just add for every viz that takes collection vars. 

Two options: 
1. Add new column to map called displayOrder and if plot.data sees this it'll rank the values if possible. Nice because avoids new argument but adds a lot for a very specific case
2. Add `collectionValueOrder` which lists the to-be values in their display order. Pros: easier to pass info directly from the app, and if we can't get ranking of data working here it'll be easier to send directly to the front end.

I like 2. 

The abundance app already returns `computedVariableDetails$variableId` which lists the vars in order. This should be send into the `collectionValueOrder` arg.

**Comment by asizemore** [comment]
For now we might be able to just punt on this in plot.data. Eventually a collection should be able to have an order, and it could come out as collectionVariable.vocabulary. For the current need, should just rename computedVariableDetails.variableId to whatever axis var vocabulary.

**Comment by d-callan** [comment]
i feel like we talked about this but i cant remember details any longer. is this for the ranked abundance app specifically? generally, I see two ways we can set orders to display values in:

1. the client does it based on a vocabulary in the study metadata. this is i believe, and i think should be, the defaul behavior
2. the client does it based on the results of an applied ranking method. in this case the data might have been ranked here or in the compute service. and it seems plot.data's job in either case would be to provide a 'rankedOrder' property in the response. if present this would override any vocabulary for that variable/ collection.

**Comment by asizemore** [comment]
My plan for the short term at least is have the client do it based on a vocabulary. Turns out we're already returning this info (we thought ahead!) and so all we really need to do is wrangle the list of variables and traces into the necessary shapes. 

I'm about halfway through the implementation, but had left this open in case for some reason it doesn't work, and we have to go with 2. Hoping to prevent opening and closing these issues a bunch of times :)

**Comment by d-callan** [comment]
For clarity, when you say vocabulary do you mean something plot.data is already returning? I typically use vocabulary to mean something from study metadata. But I guess you're using it like 'conputed variable vocabulary' ?

**Comment by asizemore** [comment]
> I typically use vocabulary to mean something from study metadata

yes that's what i mean - sorry i wasn't clear. web-eda uses the vocabulary from the study metadata to reorder labels/boxes/etc, so i'm hoping to tap into that functionality.
The ranked abundance response includes a list of the variables in order, so my plan is to take that list, format it like study metadata vocabulary, and then use the reordering-based-on-vocabulary machinery to handle it all on the front end.

**Comment by asizemore** [comment]
Will be handled on the front end. See https://github.com/VEuPathDB/web-eda/issues/1084

Nothing to QA
