### ISSUE TITLE
Backend: pass around number of unique values

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/plot.data#156]
**Must be solved before we introduce gradient colormaps widely**

We plan on having three overlay (color) funnels:
1. categorical vars -> categorical colormap
2. continuous (dataShape) vars with < 9 values in the vocabulary (not subset) -> discrete sequential colormap
3. continuous (dataShape) vars with >= 9 values.

Right now we can't tell 2 from 3. It's important to be able to distinguish between these two so that we can handle the data appropriately. For example, we can use trend lines for 2 but not for 3.

This issue arose out of a discussion around #134

**Comment by danicahelb** [comment]
talked to @asizemore and we can get around needing this ticket in place to be able to roll out continuous variables on map. this will be needed for gradients on other viz tools though.

@d-callan @bobular please confirm that this is correct

**Comment by d-callan** [comment]
I think that's true bc we aren't planning to use a true gradient in the map. Also, I think there's a request outstanding (or possibly already resolved?) for there to be a vocabulary provided for low cardinality continuous variables bc it was causing buggy legends and things. We could use the vocabulary instead of a count of values if/when we have it.

**Comment by asizemore** [comment]
@d-callan was the plan of the vocabulary ticket to pass the vocab to plot.data? If i remember correctly i think we were running into issues with not having the info necessary to handle gradient colormaps there

**Comment by d-callan** [comment]
I wasn't trying to suggest anything specific wrt implementation yet.. mostly just realizing a vocab and a unique value count are potentially a bit redundant. the data service could always find the length of the vocab and send a unique value count to plot.data that way if needed, and if we have a vocab already but not a unique values count.....

**Comment by asizemore** [comment]
ahh i see. Sounds good!

**Comment by bobular** [comment]
Option 3 is -> continuous sequential colormap, right? @asizemore

**Comment by asizemore** [comment]
option 3 -> any continuous gradient colormap. May be sequential, may be diverging, may be converging. But yes option 3 goes to a continuous colormap :)

**Comment by d-callan** [comment]
Seems option 2 could be sequential, diverging etc as well. Only difference is it's discretized

**Comment by d-callan** [comment]
we dont need this for the map. and now that we are (or at least plan to) use a gradient for all continuous vars regardless of cardinality, we may not need it at all. im going to close it, and if we decide im wrong we can always reopen.
