### ISSUE TITLE
Backend: Numeric overlay with no data returns overlayVariableDetails with value null

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/plot.data#160]
Example: GEMS no filter
<img width="1762" alt="Screen Shot 2022-04-21 at 5 06 08 PM" src="https://user-images.githubusercontent.com/11710234/164552853-15ce31ea-2dde-49b6-9bab-6f8b63cddb8a.png">

Looking into this briefly it's my bug - i missed updating the check here (`class-plotdata.R` line 242) for continuous variables.

**Comment by asizemore** [comment]
Just checked and this is working now. Closing ticket. Outreach please reopen if you see otherwise!

**Comment by danicahelb** [comment]
it works, thanks!

<img width="959" alt="image" src="https://user-images.githubusercontent.com/25450900/173611715-4b0b2a8d-7dae-447f-9c12-3b0711ae7450.png">
