### ISSUE TITLE
Backend: discrete colormap support in all plot types

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/plot.data#163]
based on conversation in slack it seems we might have a need (to be confirmed/ finalized yet but i wanted to write it down while i was thinking of it) in the mapveu application for all vizs to be able to discretize continuous variables for the overlay. in eda generally though continuous variables are going to use a proper gradient, possibly excepting low cardinality continuous variables. I think that logic should possibly be clarified in a dataviz meeting before implementing this. but in either case i think continuous variables w more than some number of values (8, 10, ?) need to be able to support optionally either gradient or sequential discrete colormaps, and in the second case we need to bin the data into some user defined number of equidistant ranges, w the default yet tbd. hopefully any of that made sense..

**Comment by bobular** [comment]
I think all the summary stats (everything except scatterplot?) would still need to discretise if overlay stratifying a continuous variable.  
For example imagine if this histogram was stratified on Age (here simulated using "age group" already in 3 bins)
![image](https://user-images.githubusercontent.com/308639/165620721-b879e125-17e6-4366-a2ba-56ff5aea1df2.png)

**Comment by bobular** [comment]
If a scatterplot is "overlaid" with a continuous variable, this is only possible without trend lines, right?

**Comment by d-callan** [comment]
Think that's what we did but @asizemore  could confirm. The other option would be to provide a single trend line per panel. I don't have strong opinions.

**Comment by asizemore** [comment]
> If a scatterplot is "overlaid" with a continuous variable, this is only possible without trend lines, right?

@bobular correct! The scatterplot should return a nice error saying exactly that if you try to give it a continuous overlay and request trend lines.

Sorry i'm behind on all the other discussions on this topic! I'll try to get up to speed and provide better thoughts tomorrow!

**Comment by asizemore** [comment]
I'm proud to say i am up-to-date on the slack thread and mockups! This is going to be so cool!

Right, so if scatterplot has a continuous overlay that is not binned, so it's using the continuous gradient colormap, then trend lines don't really make sense. If the continuous overlay gets binned, so using the discretized gradient colormap, then i'm not terribly opposed to trend lines. Just a little opposed 🙂 . I'm not crazy about doing math on the binned data and then deriving meaning from the differences in those trend lines, i guess. But i dont have any math to really back that up, just a general queasiness.

**Comment by bobular** [comment]
> But i dont have any math to really back that up, just a general queasiness.

Yeah I agree. Can't put my finger on it, but it seems sketchy to me too.

**Comment by bobular** [comment]
There may not be a "mapveu application" but I think the only short-term needs of maps in EDA are to have continuous variables binned for map marker "overlay" --> https://github.com/VEuPathDB/web-eda/issues/1096

Having this for "all plot types" is not something that MapVEu would need, if it was a standalone thing, as far as I am aware.

**Comment by d-callan** [comment]
note that this would mean something like histo or line would need to be able to support TWO binning specifications, one for xaxis and one for overlay. wed probably want to introduce a BinSpec class to plot.data at that point, do some refactoring, possibly update histo and line APIs to deprecate things like the old viewport, binWidth params etc.

**Comment by bobular** [comment]
Sounds good.  So do we have any plans to have "viewports" for non-binned plots, like Scatter?  It seems that if we can handle sending all the point data to the client, there is no need to resend less when the user zooms in.

I can't remember the name of the hexagonal density-scatter plot thing, but that's effectively a binned thing that could potentially require different bin specs for x and y.

**Comment by d-callan** [comment]
i dont currently have any plans for viewports on non-binned plots. the only way wed need them is if we wanted to semantically zoom things like smoothed means in scatter or something, which i believe we said we didnt want to do. but never say never i suppose.

for the hexbin i was considering introducing a HexBinSpec in addition which would consider both axes simultaneously. but im happy to figure that out properly when we actually get there.

**Comment by d-callan** [comment]
think we ended up making a duplicate of this

**Comment by danicahelb** [comment]
@bobular @asizemore @d-callan where can i see this in action? i don't see it on qa.clinepi (unless i am looking in the wrong spot), is it just implemented for the map?

**Comment by d-callan** [comment]
It's implemented backend, but I don't think it's in use anywhere yet. When it is my understanding was it'd be for the map only.
