### ISSUE TITLE
`map-markers-overlay` sometimes fails to assign binWidth automatically (and throws 500)

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/plot.data#169]
My diagnosis so far

./R/class-plotdata-map-markers.R is the only code to call `numBinsToBinWidth` (to get the binWidth for 8 default bins)

I suspect it's not handling NAs correctly because in SCORE Seasonal, the Age variable causes this* unless Age is filtered on Age:0-100 (which gets rid of NAs).  Nearly all the continuous vars in SCORE Mozambique also have this problem, and can be resolved by broadly filtering on them first.

(* I'm talking about making a request to map-markers-overlay with an empty `config.binSpec` object in the request - in order to get the default 8 bins)

**Comment by asizemore** [comment]
Thanks @bobular ! Do you mind providing the request you made?

**Comment by asizemore** [comment]
I think your suspicion about NAs is a good one, but I might as well do a check on the data you're using

**Comment by bobular** [comment]
Sure. Is this what you need?

SCORE Seasonal

```
{
  "studyId": "SCORESL01-1",
  "filters": [],
  "config": {
    "outputEntityId": "EUPATH_0000096",
    "xAxisVariable": {
      "entityId": "EUPATH_0000096",
      "variableId": "OBI_0001169"
    },
    "latitudeVariable": {
      "entityId": "EUPATH_0035127",
      "variableId": "OBI_0001620"
    },
    "longitudeVariable": {
      "entityId": "EUPATH_0035127",
      "variableId": "OBI_0001621"
    },
    "geoAggregateVariable": {
      "entityId": "EUPATH_0035127",
      "variableId": "EUPATH_0043205"
    },
    "showMissingness": "noVariables",
    "valueSpec": "count",
    "binSpec": {},
    "viewport": {
      "latitude": {
        "xMin": 6.953691427897033,
        "xMax": 10.212219258788627
      },
      "longitude": {
        "left": -7.102661132812501,
        "right": -1.6094970703125002
      }
    }
  }
}
```

**Comment by asizemore** [comment]
Yes that's perfect! Thank you!

**Comment by danicahelb** [comment]
Hey @asizemore and @bobular is there anything specific outreach should QA for this ticket?

**Comment by bobular** [comment]
> Hey @asizemore and @bobular is there anything specific outreach should QA for this ticket?

Before the back end was fixed by @asizemore, in SCORE Mozambique, pretty much all of the numeric variables gave errors for the map viz.  You could get round them by filtering on the numeric variables (effectively removing NAs).

Now they should work without filtering.

Don't do too much testing - we will roll out the "final" map viz after work on this new ticket: https://github.com/VEuPathDB/web-eda/issues/1191

**Comment by asizemore** [comment]
@bobular btw this should have been rolled out to the qa backend by now

**Comment by asizemore** [comment]
by that i mean looking at the tags that got built in jenkins, a recent enough version of Rserve succeeded that would be carrying the fix :) and this version is on the qa branch of tagger

**Comment by bobular** [comment]
I probably wasn't clear either.

I think I meant that nobody other than developers working on the new branch(es) saw the 500.  So it's not something QA people ever saw.

All good now, that's the main thing!
