### ISSUE TITLE
Legend text formatting for continuous overlays needs styling fix

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/plot.data#174]
Legend text formatting for continuous overlay variables is confusing. for example, `[89,657]` looks like 89.6K instead of 89 - 657

<img width="247" alt="image" src="https://user-images.githubusercontent.com/25450900/173109689-eebb8d8e-2bc7-4dad-81e5-83138e70664a.png">

Can we change the formatting please? Perhaps to: `[89 to 657]`

**Comment by danicahelb** [comment]
I'm willing to see what it looks like with better spacing and formatting of the numbers before deciding. Its just so hard to read right now!

**Comment by danicahelb** [comment]
@asizemore, I assigned you since you volunteered in 8/17/2022 implementation meeting

**Comment by asizemore** [comment]
deployed to QA

**Comment by aaronwlsong** [comment]
Looks good now, closing ticket.
---------------
Study: SCORE Niger S. haematobium Cluster Randomized Trial
Viz tool:  Map
Variable: School-age children in village count
<img width="1602" alt="Screen Shot 2022-08-26 at 10 25 04 AM" src="https://user-images.githubusercontent.com/61077845/186926563-da9ebcb6-9202-4dfc-bca6-f12c8e2b1c26.png">
