### ISSUE TITLE
Map: returning extra bins

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/plot.data#175]
Score mozambique, var= School age children treated in village (%)

<img width="1695" alt="Screen Shot 2022-06-13 at 4 19 07 PM" src="https://user-images.githubusercontent.com/11710234/173438131-dd8f22d6-7ea4-4341-84cd-904b9dba7583.png">

@bobular noticed that we're returning an extra bin that's empty when the map overlay var is continuous. Why does this happen?

**Comment by asizemore** [comment]
Ready for testing, @bobular !

**Comment by bobular** [comment]
Regarding the (now intermittent) extra empty bin, I looked into the code, played around with some test cases including some values that looked like `School-age children in village count` and its max value of 3926.4, and couldn't find any obvious explanations, and the tests all passed as expected.  Maybe there's no need to add the `extraBin`? Or maybe we can only do that safely after we've rewritten `cut()`?

**Comment by bobular** [comment]
I am now going to try to diagnose the 500 error.

**Comment by bobular** [comment]
This might be it:
```
Error in cut.default(x, breaks, include.lowest = TRUE, right = (closed ==  : 
  'breaks' are not unique
```

**Comment by aaronwlsong** [comment]
The issue addressed in this ticket looks good now, closing ticket. 

BTW, the var "School-age children in village count" in this study still hits 500 error in map. 

![Image](https://user-images.githubusercontent.com/61077845/174356050-301d3bbe-2afe-4a0a-8a5b-d69c8d756d60.png)


![Image](https://user-images.githubusercontent.com/61077845/174356051-6a67803e-8968-4bdd-a029-1de2ff6ba720.png)

**Comment by bobular** [comment]
Yes, thanks Weilu - I am working on that now, and I made a separate ticket
https://github.com/VEuPathDB/plot.data/issues/179
