### ISSUE TITLE
Mbio: diabimmune "Age" gives 500 in histogram

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/plot.data#184]
<img width="1739" alt="Screen Shot 2022-07-15 at 11 07 50 AM" src="https://user-images.githubusercontent.com/11710234/179251680-6a6ef4c1-2458-4d6b-a9cd-1c10f4ca8137.png">

Clues: 
- The histogram on the browse and subset tab looks good
- Other vars on the histogram are fine

**Comment by danicahelb** [comment]
I'm having the same issue with age viz tab histograms for the LLINEUP study! May be a related issue? https://github.com/VEuPathDB/EdaNewIssues/issues/376

**Comment by bobular** [comment]
I'm getting 500s with GEMS1 histogram viz, weight for age z-score, with the default binwidth, but only after changing the x-axis range (even slightly to -29 to 20, or even manually back to -30 to 20, which is the default annotated range.

**Comment by dmfalke** [comment]
@bobular have you captured a stack trace associate with the 500 response?

**Comment by bobular** [comment]
How would I test this after the plot.data update?  **Diabimmune (WGS)** does not seem to exist on https://feature.microbiomedb.org/mbio.feature/app

**Comment by bobular** [comment]
> I'm getting 500s with GEMS1 histogram viz, weight for age z-score, with the default binwidth 0.08, but only after changing the x-axis range (even slightly to -29 to 20, or even manually back to -30 to 20, which is the default annotated range. You can rescue the plot (no 500) by setting the binwidth a bit higher e.g. 0.1 (though 0.09 does not do it)
> 
> Update: seems to affect other X for age z-score variables. It doesn't affect Household wealth numeric. I think it's something to do with those small binwidths.


Happy to report weight for age z-score is now working fine for GEMS1 !

**Comment by bobular** [comment]
@SheenaTomko will check with Jay to see if it's loaded - thanks!

**Comment by bobular** [comment]
Thanks @jaycolin 

Looks good now, closing this ticket.

![image](https://user-images.githubusercontent.com/308639/184027932-7d0e80a0-afd4-434b-ab08-6111a14593e8.png)
