### ISSUE TITLE
Ranked abundance: Brief message about no plottable data when selecting overlay

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/plot.data#192]
Only happens on ranked abundance *box plot*

To reproduce, open the ranked abundance box plot. A plot appears. Select a strata variable. A brief message about no plottable data appears (see my super fast screenshot of the message)

<img width="1445" alt="Screen Shot 2022-07-15 at 10 49 26 AM" src="https://user-images.githubusercontent.com/11710234/179248089-37faa1b2-4af6-4aab-bbdf-9a4994d120a9.png">

It only happens if we're going from no strata vars to having one strata var. I briefly looked into this a while ago and I want to say it was `outputSize` in `BoxplotVisualization.tsx` that briefly becomes 0 which causes the error? 

I recommend waiting for VEuPathDB/web-eda#1244 to be merged before addressing this issue

**Comment by asizemore** [comment]
deployed to feature, @SheenaTomko 
to QA, please check that when adding a strata var for the first time in the ranked abundance box plot, no error message about a lack of plottable data appears (see first screenshot above).

**Comment by aaronwlsong** [comment]
Replicated the case. Looks good now, closing ticket.

-----------
Use study **BONUS-CF** as example.
Step1: open a new  ranked abundance box plot, not choosing strata variable:
<img width="1568" alt="Screen Shot 2022-08-25 at 6 10 27 PM" src="https://user-images.githubusercontent.com/61077845/186778031-6788eeff-309d-4e1d-a157-3af397a169b5.png">

Step 2: choose an overlay variable: "Host body product".
<img width="1423" alt="Screen Shot 2022-08-25 at 6 11 03 PM" src="https://user-images.githubusercontent.com/61077845/186778111-b743142b-3667-448b-9b06-ec215ca646a2.png">

Then, tested another strata choice: facet, use study** Bangladesh 5yr**.
Step 1. open a new  ranked abundance box plot, not choosing strata variable:
<img width="1434" alt="Screen Shot 2022-08-25 at 6 16 11 PM" src="https://user-images.githubusercontent.com/61077845/186778468-6ee44d31-2452-4b04-a6a3-b018d0442993.png">

Step 2: choose an overlay variable: "Host body product".
<img width="1403" alt="Screen Shot 2022-08-25 at 6 16 38 PM" src="https://user-images.githubusercontent.com/61077845/186778481-d08cbb30-b137-4507-a02f-a1f74f894399.png">
