### ISSUE TITLE
Empty map-markers-overlay response has malformed `binSpec.value`

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/plot.data#200]
To reproduce:

1.
qa.clinepidb.org
SCORE S. mansoni Cluster Randomized Trial
Filter on Country = Cote d'Ivoire
Go to either map (FSM or viz)
Choose Participant -> Occupation as the variable

(The thrust of the example is that Cote d'Ivoire participants don't have any occupation data.)

2.
OR... zoom in to any part of the map with no data!!

The response is 
```
{
	"binSpec": {
		"type": "binWidth",
		"value": null
	}
}
```
but the spec says `binSpec.value` must be a `number`, though it is optional. Actually the entire `binSpec` part is optional.

One option is to change the spec and update the client validation.

**Comment by SheenaTomko** [comment]
Results show markers with no color and the number 0 inside. Looks good
