### ISSUE TITLE
Beta diversity: Receiving invalid PlotReference error with overlay

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/plot.data#201]
In beta div app, we see a 500 from the backend if we try to select an overlay (categorical or continuous).

<img width="995" alt="Screen Shot 2022-12-14 at 6 00 51 AM" src="https://user-images.githubusercontent.com/11710234/207577902-3ae6fddf-bd15-43f4-a004-c5b158a758fa.png">

Here's the request
```
{"studyId":"EMP_1927_HMP_V13-1","filters":[],"config":{"outputEntityId":"EUPATH_0000809","overlayVariable":{"entityId":"EUPATH_0000096","variableId":"ENVO_01000739"},"showMissingness":"FALSE"},"computeConfig":{"collectionVariable":{"variableId":"EUPATH_0009252","entityId":"EUPATH_0000809"},"betaDivDistanceMethod":"bray","outputEntityId":"EUPATH_0000809"}}
```

The Rserve output:
```
Error in validObject(.Object) : 

invalid class ?PlotReference? object: Plot reference must be one of xAxis, yAxis, zAxis, overlay, facet1, facet2, geo, latitude, longitude
```

I'm not totally convinced this is really a plot.data error, because it only happens in beta div scatter. XY relationships scatter and alpha div scatter overlays work just fine. beta div scatter with different dataset does give in the error. Maybe a data service issue? I took a quick peek but nothing looked awry

**Comment by d-callan** [comment]
fixed in the data service
