### ISSUE TITLE
Mosaic plot (2x2) - statistics tab backend 2 (diagnostic test performance)

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/plot.data#203]
related to https://github.com/VEuPathDB/web-eda/issues/1384 and https://github.com/VEuPathDB/plot.data/issues/202

Mockups: https://www.figma.com/file/Su1eNm3Bby85CfrnX42L7q/2x2-table-UI?node-id=317%3A623&t=ZCxlWaPOOG1AbgKr-0

The following statistics would be nice to roll out in b62. Implementation in b63 Ok:

1. Sensitivity
2. Specificity
3. PPV
4. NPV

**Comment by d-callan** [comment]
this should have been closed w #202

**Comment by nkittur-uga** [comment]
This ticket will be QAed once the front-end tickets are implemented.

**Comment by danicahelb** [comment]
It seems like values for (i) Sensitivity and PPV are swapped; and (ii) values for Specificity and NPV are swapped

**Please check & fix calculations for:**
- Sensitivity
- Specificity
- PPV
- NPV


_More info:_ 

These are the results from GEMS1 with no subsetting:


![Image](https://user-images.githubusercontent.com/25450900/222225168-2f2855fa-05f3-4dc6-a381-a097cce95a7f.png)


Quadrant values should be:

- A = 1747
- B = 509
- C = 7691
- D = 12618

I've hand checked the calculation for Prevalence, Odds ratio, and Risk ratio, using the formulas in our more information dropdown.
- Sensitivity = 0.19
- Specificity = 0.96
- PPV = 0.77
- NPV = 0.62

Note that the 2x2 table is NOT being set up correctly, @jernestmyers is addressing that in this ticket: https://github.com/VEuPathDB/web-eda/issues/1663

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/25450900/222214024-c4674cfa-cf3b-4d40-b044-150dbae17216.png">

**Comment by moontrip** [comment]
@danicahelb Here is the backend response with the same example you used above. As you can see the stats table in the frontend reflected the backend response correctly, so it would be a backend issue if something is incorrect.

![mosaic stats GEMS1 backend response01](https://user-images.githubusercontent.com/12802305/222242480-0c7cb027-9648-428d-a2c5-7080d427f8d2.png)

**Comment by d-callan** [comment]
fixed in rserve v5.1.3

**Comment by danicahelb** [comment]
I just checked and am seeing the exact same table
https://github.com/VEuPathDB/plot.data/issues/202

**Comment by danicahelb** [comment]
@dmfalke this one was probably also not deployed.

**Comment by danicahelb** [comment]
@d-callan point estimates & 95% CI for diagnostic test performance now look correct. Is there a reason p-values are not being calculated?



![Image](https://user-images.githubusercontent.com/25450900/223275557-65bc4044-0322-4dbe-9cdf-050d82ddc5de.png)

**Comment by d-callan** [comment]
i thought we were asking people to look to chisq or fishers for pvalues based on sample size?

**Comment by danicahelb** [comment]
We don't need p-values for diagnostic test performance statistics, thanks
