### ISSUE TITLE
Visualizations: categorical overlay, find counts for customisable N<=7 + other

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/plot.data#205]
see https://github.com/VEuPathDB/EdaDataService/issues/238 for details

**Comment by d-callan** [comment]
Important: very likely we dont need this for SAM so much as the map viz in EDA. this ticket is NOT a prioirity for b63.

**Comment by d-callan** [comment]
since the floating charts will need this for SAM, im going to generalize this ticket to cover all plot classes and include it as a b63 priority

**Comment by danicahelb** [comment]
backend ticket, nothing to QA
