### ISSUE TITLE
SAM floater overlay for SCORE S. mansoni country variable broken by quote/apostrophe in Cote d'Ivoire

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/plot.data#230]
I thought we had a ticket for this but it seems that we don't.

I just confirmed this is not a problem with regular EDA.  It's likely something to do with the new overlayConfig and the need to escape special characters in R (I have a vague recollection that the container log errors were from R).

It gives a 500 error.

@d-callan could you triage please?

**Comment by dmfalke** [comment]
I moved this to plot.data. Feel free to move to a more appropriate repo, if needed.

**Comment by d-callan** [comment]
i just closed the duplicate in the data service.
