### ISSUE TITLE
Parent issue: bipartite network class for correlation

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/plot.data#234]
To Dos:

- [x] #229 
- [x] #232 
- [x] #233

**Comment by asizemore** [comment]
Note we'll have to make a choice at some point of which network methods we ask something like igraph to do and which we want to do ourselves. For example, let's say we have the network in a matrix format. The weighted degree is just the row/col sums. Why would we take the time to convert to an igraph format for that? But something like community detection is worth going to igraph for.

**Comment by d-callan** [comment]
im going to close this. as specific needs arise, we can file individual tickets.
