### ISSUE TITLE
500 server error for smoothedMean/smoothedMeanWithRaw at scatter plot viz

### ISSUE THREAD

**Issue by moontrip** [VEuPathDB/plot.data#37]
Seems like a backend issue - it is reproducible at [feature site](https://feature.clinepidb.org/ce.feature/app/eda/DS_841a9f5259) for scatter plot viz.

When using xVariable: sleeping rooms in dwelling; yVariable: Persons living in house; overlay variable: Country (or Floor material - only tested these two), it works fine for `valueSpec: raw` and `bestFitLineWithRaw`. However, when using `valueSpec: smoothedMean` or `smoothedMeanWithRaw`, it shows 500 internal server error.

On the contrary, when using overlay variable with two stratifications like `Coking Fuel (Charcoal, wood, etc.)`, then all `valueSpec` options worked fine.

**Comment by d-callan** [comment]
this should no longer produces a 500. instead of failing, we pass along the error R puts up for the troublesome groups that we cant calculate smoothed mean values for.
