### ISSUE TITLE
add arg to group fxns to make noStatsFacet optional

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/plot.data#4]
if a group fxn relies on another (ex: groupSmoothedMean finds max groupSize to know what method to use) we dont want to collapse the data w noStatsFacet. but when the plot classes call group fxns they do want to collapse the data to one row per group.

**Comment by asizemore** [comment]
I'm not sure I quite understand -- in the groupSmoothedMean/groupSize example, groupSize currently does not call noStatsFacet. Is the issue that groupSize should have an optional call to noStatsFacet (via an additional arg)? Or that any of the group functions that currently call noStatsFacet (groupMean, groupFences, etc.) should get an additional arg to make their noStatsFacet call optional, regardless of if these functions are currently called by another group function?

**Comment by asizemore** [comment]
Closed with PR #20

**Comment by asizemore** [comment]
Closed with PR #20
