### ISSUE TITLE
smoothedMeanY and smoothedMeanSE incorrectly return string array when smoothedMeanError exists

### ISSUE THREAD

**Issue by moontrip** [VEuPathDB/plot.data#40]
@d-callan I have tested the case when smoothedMeanError exists, i.e., not empty string but with error messages. One issue I found is that for the error case, smoothedMeanY and smoothedMeanSE incorrectly return string array, not number array. As we have discussed before, those two parameters should return `number array` as written in data API doc. For non-error cases, they return number arrays correctly. 

Can you please change this?

**Comment by d-callan** [comment]
this should be updated now.

**Comment by moontrip** [comment]
Thanks @d-callan for your quick fix 👍 . Will test it after a while (to be reflected at the site :) )
