### ISSUE TITLE
Boxplot: backend response for points option seems to be inconsistent

### ISSUE THREAD

**Issue by moontrip** [VEuPathDB/plot.data#51]
Discussed with @d-callan at Slack and she recommended to make this issue.

With the refactoring of boxplot component and its viz, I have a chance to test two options for points POST such as `points: 'outliers'` and `points: 'all'`: especially for the latter as the backend now responds `rawData` parameter. The two options worked fine for displaying plots but it appears to me that there exists a bug from the backend. 

Here is an example (also visible at screenshots): X = Breastfed; Y = Age at eligibility form completion. Note that I am relying on the `entityName.VariableName` parameter for X-axis (indep. axis) label, which is the format of the following:

```
      "EUPATH_0000096.EUPATH_0010371": [
        "Exclusively breastfed",
        "Not breastfed",
        "Partially breastfed"
      ],
```

This first screenshot is with `points: 'outliers'`
![boxplot-breastfed-outliers1](https://user-images.githubusercontent.com/12802305/124646619-e11f0580-de62-11eb-9b78-2ddc27479fbb.png)

The second screenshot is with `points: 'all'`
![boxplot-breastfed-all2](https://user-images.githubusercontent.com/12802305/124646683-f6942f80-de62-11eb-9063-09170bad91ed.png)

I don't know which one is right but assuming that the outlier one (the first screenshot) is correct, then the rawData for Exclusively breastfed seems to be Not breastFed at outlier, Not breastfed one at rawData is Partially breastfed, and finally Partiall breastfed at rawData is Exclusively breastfed. In other words, those two options seemed to return different array order: I checked that both cases returned the same EUPATH_0000096.EUPATH_0010371 values in order.

**Comment by d-callan** [comment]
found the bug and pushed a fix to plot.data (will wait to make a release/tag until after demo july 19)
