### ISSUE TITLE
Histogram: return integer binWidths for integer-like variables.

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/plot.data#55]
For reasons discussed [here](https://github.com/VEuPathDB/web-eda/pull/120#issuecomment-883749798)

**Comment by d-callan** [comment]
@asizemore if youve got the bandwidth and are interested

**Comment by asizemore** [comment]
Yup I can take it

**Comment by asizemore** [comment]
To clarify, is the intended functionality 
1. if a binWidth is not specified (`= NULL`), then we return an integer binWidth for integer-like vars, or
2. regardless of the number of bins or binWidth specified, we'll always ensure the binWidth is an integer for integer-like vars?

**Comment by d-callan** [comment]
The first

**Comment by bobular** [comment]
Sounds good. Do you have access to the variable metadata/annotation information on the back end?

**Comment by asizemore** [comment]
Made a simple fix: see PR #58 
Assumes we can determine if a variable `x` is ineger-like by testing that `x %% 1` is equal to 0.

**Comment by d-callan** [comment]
@asizemore can we close this?

**Comment by asizemore** [comment]
Yup! Closed with PR #58
