### ISSUE TITLE
Visualizations: New boxplot labels response needs to be string type, even with categorical number vars

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/plot.data#57]
Barplot (which also has a `label` response) is fine, but boxplot is returning numbers for, e.g. PRISM Seizures duration

```
{
	"label": [
		0,
		1,
		2,
		7
	]
}
```

**Comment by d-callan** [comment]
@asizemore will your other fixes re cat nums impact this? or can it if not?

**Comment by d-callan** [comment]
Yea it should I suppose. Do we get extra points for fixing it twice?

**Comment by d-callan** [comment]
Best not to assume plot.data will only serve the data service though..

**Comment by danicahelb** [comment]
I'm not sure if this issue is not fixed, or if I hit a new bug when testing with SCORE S. mansoni Cluster Randomized Trial
x= study timepoint
y= birth year

![image](https://user-images.githubusercontent.com/25450900/130281249-cfb450ac-963f-42b0-8c32-67e5a15cbf47.png)

**Comment by danicahelb** [comment]
I get a similar issue with GEMS1:

![image](https://user-images.githubusercontent.com/25450900/130281515-7562e548-38f4-4095-98f1-39057a1325bb.png)

**Comment by danicahelb** [comment]
@d-callan @asizemore assigning back to you, issues haven't been addressed

**Comment by d-callan** [comment]
this might depend on veupathdb/edasubsettingservice#19
when i test locally the plot.data bug looks to be resolved.

**Comment by d-callan** [comment]
this also looks to be resolved on qa after finally getting recent backend changes properly deployed. however, its no qa-able yet, bc of this other bug in the subsetting service. so i suppose ill leave it open..

**Comment by bobular** [comment]
Should be tested against a "pinned" new study

**Comment by asizemore** [comment]
@danicahelb I think this should be moved to Ready for Testing -- just looked briefly at qa site, PRISM2, boxplot, with Respiratory Rate as the x axis var and looking good!

<img width="804" alt="Screen Shot 2021-09-29 at 12 05 15 PM" src="https://user-images.githubusercontent.com/11710234/135306754-32d45835-6e7f-408e-8c4b-35bbf48e1df7.png">
..

**Comment by danicahelb** [comment]
Issue also looks fixed with 'Household wealth index, categorical' in GEMS1
![image](https://user-images.githubusercontent.com/25450900/135517061-fa663796-4ac2-47d0-836d-5dfa85088551.png)

And with 'Study timepoint' in SCORE S. mansoni
![image](https://user-images.githubusercontent.com/25450900/135517684-d49b6e78-f0d7-4af1-bd0a-257a87025b0d.png)
