### ISSUE TITLE
Set consistent env somehow in .dev

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/plot.data#60]
Tests fail depending on your timezone for ex

**Comment by asizemore** [comment]
Looks like we can use `.onLoad` to set the timezone ([example](https://github.com/tidyverse/dplyr/blob/bbcfe99e29fe737d456b0d7adc33d3c445a32d9d/R/zzz.r), [discussion](https://stackoverflow.com/questions/20223601/r-how-to-run-some-code-on-load-of-package)) on package load?

**Comment by asizemore** [comment]
I'm reading through Hadley's chapter on environments now, but was able to get the onLoad strategy to work very quickly so gave it a [shot](https://github.com/VEuPathDB/plot.data/pull/63).

**Comment by asizemore** [comment]
found the `dotenv` [package](https://cran.r-project.org/web/packages/dotenv/dotenv.pdf) which works well. See second commit on the above draft pr for example.
Do you have a preference for one vs the other? The onload approach means we don't have to do anything extra, but I'm not sure if we would want users to have their timezone changed when they load the package. On the other hand setting env vars in .dev with dotenv means users don't have to deal with it but during dev we have an extra step of running `load_dot_env(file=".dev/.env")`.

**Comment by asizemore** [comment]
Closed with PR #63
