### ISSUE TITLE
determine possible options for value arg in scatter class

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/plot.data#7]
currently the options are 'smoothedMean', 'density', and 'raw' . but all options actually return raw data, w smoothed mean and density just returning those data in addition to the raw data. do we want this? or break raw into its own boolean arg? or something else?

**Comment by d-callan** [comment]
After some conversation in the data viz channel I think the options we need are 'raw', 'density', 'smoothedMean' and 'smoothedMeanWithRaw'

**Comment by asizemore** [comment]
Closed with PR #14
