### ISSUE TITLE
Backend: mosaic hardcodes 'panel' which affects handling by json helpers

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/plot.data#71]
The `addStrataVariableDetails` handles a column called 'panel', which should be present if we have two facets. However, the mosaic returns a data table that specifically has a column called 'panel' (see `panelTable`). 
If we have no facets with name 'panel', then when we write to json we get a funky output because we don't handle the 'panel' column. This subtle bug was hidden because often we call facet vars 'panel'. 

One option is to call the 'panel' column something different in `panelTable`, but we'd need to change the api in the DS as well. 

See testing failures in PR #69 for more details.

**Comment by asizemore** [comment]
Only becomes an issue when we have facets.

**Comment by d-callan** [comment]
The panel family of fxns are probably supposed to be assigning to [[panel]] rather than $panel, similarly to the group fxns..

**Comment by d-callan** [comment]
if that turns out to be all thats necessary to get this working, id like to just do it and have it done
