### ISSUE TITLE
Backend: split entity name and var id when assigning xVariableDetails

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/plot.data#81]
Found when working on the statsTable since I'll need to do something similar -- when we form variable details we need to always pass variableId not toColNameOrNull. 

Fix - verify all uses of `makeVariableDetails` are using variableId not the column name

**Comment by asizemore** [comment]
Closed with PR #82

**Comment by danicahelb** [comment]
@asizemore how do i qa this?

**Comment by asizemore** [comment]
This was a very very minor change that really just covered some exposed bases and didn't originally have an actual bug linked. As long as variable names are looking good on a few x axes then I would call it done :)

**Comment by danicahelb** [comment]
OK, its done. thanks!
