### ISSUE TITLE
Odds ratio and relative risk not showing up

### ISSUE THREAD

**Issue by nkittur-uga** [VEuPathDB/plot.data#87]
Odds ratio and relative risk and not showing up correctly. See example below. (To recreate: GEMS1 study-> 2 x 2 plot -> X=case or control participant; Y= Giardia, by ELISA.)
<img width="388" alt="Screen Shot 2021-08-26 at 4 30 17 PM" src="https://user-images.githubusercontent.com/67710160/131035791-827594df-f441-4574-a97c-351faae75b1b.png">

**Comment by d-callan** [comment]
found the culprit. the mosaic class in plot.data will try to determine which stats (chisq vs relative risk and odds ratio) to use based on the data it receives, unless a specific statistic is requested. it was doing the check for the number of unique values before removing rows w missing axes data. and so it thought one of the two vars actually had 3 unique values, and consequently tried to return chisq results instead. im fixing this bug in plot.data, and have already updated the 2x2 endpoint in the data service to explicitly request odds ratios and relative risk rather than trust plot.data to infer thats what we want.

**Comment by nkittur-uga** [comment]
Upon QA of this ticket, Odds ratios and Relative risks (and 95% CIs for each) are now available in the table so that passes QA. However there is an issue of what group is being used as the reference group for this calculation, described below.

Example: GEMS1 study-> 2 x 2 plot -> X= Case or control participant; Y= Cryptosporidium, by ELISA.
Here we see in the plot that 11.9% of cases have crypto, and 6.4% of controls.

I am expecting an odds ratio of >1 because the plot shows almost twice as many cases infected with crypto compared to controls. 

However, I see that the odds ratio is 0.5081. So the odds ratio is clearly being calculated in the reverse way. This odds ratio says: "Cases are less likely to not have crypto infection compared to controls." While this is not wrong, it is certainly confusing. 

The default in the EDA is that the first value in the Y axis var is the "event". In the Y axis var "Cryptosporidium, by ELISA", the first value is NO and the second is YES. That's how NO (not being infected with crypto) is ending up as the event. 

Possible solutions for this issue (discussed with Danica and Sheena)--

Option 1: Leave out statistics table for Phase 1. Put in a placeholder saying "Coming soon". Re-implement in future when users can choose the reference group (like in shiny apps on live site).

Option 2: Frame a sentence below the statistics table in this format. 
The odds of "Case" for "Case or control participant" being "No" for "Cryptosporidium, by ELISA" is 0.5081 as compared to "Control". 

While this sentence looks clunky, it does accurately tell you what the odds ratio is being calculated for.

NOTE: Nothing needs to change in R x C for either phase 1 or 2 with respect to this issue. It affects 2 x 2 table only.

**Comment by bobular** [comment]
Just confirming here that the vocabulary order for this variable EUPATH_0011000 is "No", "Yes"

**Comment by nkittur-uga** [comment]
Yes, that is correct.

**Comment by danicahelb** [comment]
I created https://github.com/VEuPathDB/EdaNewIssues/issues/134 for the issue with OR and RR being calculated backwards in 2x2 tables.

Since OR & RR and associated 95% CI are now showing up, I am closing this ticket.
