### ISSUE TITLE
Backend: temporarily remove plot.data constraints and validation on data shape

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/plot.data#90]
This will let veupathdb/edadataservice#88 work as intended, and let plot requests succeed w the new constraints there. there is a related issue to properly update these in #88 here. this is a temporary measure, to see how we like the new constraints and how severe a problem categorical numbers are going to be in eda. if we dont like the new constraints we can revert this. if we do like them, then we can proceed w #88.

**Comment by danicahelb** [comment]
seems OK, but I am waiting on https://github.com/VEuPathDB/web-eda/issues/310 to pass qa to move to 'Complete'
