### ISSUE TITLE
General: 500 Internal Server Error for age variables across studies, in both subsetting & viz histograms 

### ISSUE THREAD

**Issue by sweverschulman** [VEuPathDB/plot.data#95]
I have received "500 Internal Server Error" when bothing trying to view variable in SCORE Rwanda and 5 Country. I have also received the same error when trying to visualize age in Wash B Kenya study. I am attaching pictures to this issue. 

**Subsetting tab**
![Screen Shot 2021-09-15 at 12 39 15 PM](https://user-images.githubusercontent.com/62298921/133490714-94a56183-a199-4a8b-b92e-3a3b83a4a12d.png)

**Viz tab**
![Screen Shot 2021-09-15 at 2 42 25 PM](https://user-images.githubusercontent.com/62298921/133491022-f9a0fdc9-1b63-4785-aa4d-5f216fa90f77.png)

**Comment by d-callan** [comment]
pushed to master and tagged plot.data v1.2.2 and rserve v1.3.6

**Comment by SheenaTomko** [comment]
Checked in SCORE Rwanda, 5 country, and WASH-B Kenya. Only fixed in WASH-B Kenya, since that's the only one that's been reloaded recently. Will consider this closed and assume issue will be fixed in other studies on reloading
