### ISSUE TITLE
Visualization: Error page in box plot when choose certain variables 

### ISSUE THREAD

**Issue by aaronwlsong** [VEuPathDB/plot.data#97]
In india_cohort study, when I choose: x=" ITN bednet count, treated >6 months ago", or " ITN bednet count, treated >6 months ago", and y="age", the website is down (see pic) and refresh and reload cannot exit that webpage. I need to click the logo of "CliEpiDB" on left top to go back homepage, and then reselect my study and analysis process. 

![image](https://user-images.githubusercontent.com/61077845/134701046-274874a6-d05f-4e06-87df-2fa7119211a7.png)

**Comment by d-callan** [comment]
plot.data v1.2.4

**Comment by sweverschulman** [comment]
reviewed bug in the india_cohort study and seems to have been fixed.
